[package]
name = "contrast"
version = "0.1.0"
authors = ["Nicolas Sentout <nicodufcbas@hotmail.fr>"]
edition = "2018"

[dependencies]
luminance = "0.30.1"
luminance-glfw = "0.5.4"
luminance-windowing = "0.2.4"
nalgebra = "0.17"
rand = "0.4"
mark_macro_derive = { path = "mark_macro_derive" }